### ISSUE TITLE
Unable to Use targetScan function with mapply

### ISSUE THREAD

**Issue by compbiolover** [fischuu/hoardeR#6]
Hi @fischuu,
I have been using hoardeR for a project and it appears that there is an issue when using it with mapply. Instead of returning the data frame as expected it returns the following. I am providing my test code and will be happy to provide more information. Thanks for all your hard work on this package. 
`test <- mapply(targetScan, mirna=c("hsa-miR-99b-5p", "hsa-miR-99b-3p", "hsa-miR-99a-5p"), species = c("Human", "Human", "Human"), release =c("7.2", "7.2", "7.2"), maxOut = c(5,5,5))'
![Screen Shot 2022-02-08 at 19 25 14](https://user-images.githubusercontent.com/39838470/153098466-90badd30-4936-47bf-8bbb-6722813609ea.png)

**Comment by fischuu** [comment]
Hi,
`targetScan()` returns actually a matrix with 4 columns and `maxOut` rows (i.e. in your case a 5x4 matrix) for each miRNA. However, `mapply` tries to simplify the output by default, meaning it tries to create a single matrix and/or vector for all the joint calls.

Of course, in your case this is not possible and you would like to keep the list of matrices (=each list item represents the output matrix per miRNA), so you need to set `SIMPLIFY=FALSE` (this option is really capitalised...). 

So, the complete command that should do what you want is

```
test <- mapply(targetScan, mirna=c("hsa-miR-99b-5p", "hsa-miR-99b-3p", "hsa-miR-99a-5p"),
               species = "Human", 
               release = "7.2", 
               maxOut = 5, 
               SIMPLIFY=FALSE)
```
Here, you can also rely on the recycling of vectors in R, so the input for `species`, `release` and `maxOut` does not need to be repeated. I hope this helps, in case you need more help, please let me know.

I took this issue also as motivation to rewrite the function such that it accepts vectors as input in `mirna` to avoid this problem in the future. 

Now, with the latest package version here in the main branch those both calls work:
```
targetScan(mirna="hsa-miR-99a-5p", species = "Human", release = "7.2", maxOut = 5)
```
and

```
targetScan(mirna=c("hsa-miR-99b-5p", "hsa-miR-99b-3p", "hsa-miR-99a-5p"), 
           species = "Human", 
           release = "7.2",
           maxOut = 5)
```

**Comment by compbiolover** [comment]
Thanks @fischuu! 
I just installed the new version and it works perfectly. Thanks for clarifying the point about `mapply`. I am still getting use to thinking about problems in `R` terms.
